example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit', ajax_submit, name='ajax_submit')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms
from . import models

class CreateWishlist(forms.ModelForm):
    class Meta:
        model = models.BarangWishlist
        fields = '__all__'

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
# Data delivery
from django.http import HttpResponse
from django.core import serializers
# Handle registrasi
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
# Handle login
from django.contrib.auth import authenticate, login
# Handle logout
from django.contrib.auth import logout
# Handle merestriksi akses halaman
from django.contrib.auth.decorators import login_required
# Handle cookies
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.http import JsonResponse, HttpResponseBadRequest
from wishlist.forms import CreateWishlist

# Menampilkan barang wishlist
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Airel Camilo Khairan',
        # Cookies
        'last_login': request.COOKIES['last_login']
    }
    return render(request, "wishlist.html", context)

# Menampilkan data berbentuk XML dan JSON
def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# Menampilkan form registrasi
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

# Menampilkan form login
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Cookies
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

# Handle logout di wishlist
def logout_user(request):
    logout(request)
    return redirect('wishlist:login')

# Menampilkan /wishlist/ajax
def wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    form = CreateWishlist()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Airel Camilo Khairan',
        # Cookies
        'last_login': request.COOKIES['last_login'],
        'form': form
    }
    return render(request, "wishlist_ajax.html", context)

# Menyimpan data dari form
def ajax_submit(request):
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    form = CreateWishlist(request.POST)
    if form.is_valid():
        instance = form.save()
        data = serializers.serialize('json', [ instance, ])
        return JsonResponse({'data': data}, status=200)
    return JsonResponse({'error':""})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login d-flex align-content-center flex-wrap flex-column align-items-center justify-content-center" style="height: 100vh;">
    <h1 class="pb-4">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>

        <div class="d-grid py-3">
            <input class="btn login_btn btn-outline-warning" type="submit" value="Login">
        </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}"><strong>Buat Akun</strong></a>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login d-flex align-content-center flex-wrap flex-column align-items-center justify-content-center" style="height: 100vh;">
    <h1 class="pb-4">Formulir Registrasi</h1> 

    <form method="POST" >  
        {% csrf_token %}  
        <table>  
            {{ form.as_table }}    
        </table> 
        
        <div class="d-grid py-3">
            <input type="submit" name="submit" value="Daftar" class="btn login_btn btn-outline-warning col-4 mx-auto"/></td>  
        </div>
    </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
            {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar">
    <h5>{{nama}}</h5>

    <!-- Handle logout -->
    <button style="border: none;"><a class="btn btn-dark" href="{% url 'wishlist:logout' %}">Logout</a></button>
</nav>

<table class="table table-dark table-hover" style="height:200px; margin:0 auto;">
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <td>{{barang.nama_barang}}</td>
        <td>{{barang.harga_barang}}</td>
        <td>{{barang.deskripsi}}</td>
    </tr>
    {% endfor %}
</table>

<!-- Sesi terakhir dilihat dari cookies -->
<p class="text-center p-4">Sesi terakhir login: {{ last_login }}</p>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar px-3">
    <h5>{{nama}}</h5>

    <!-- Handle logout -->
    <a class="btn btn-dark" href="{% url 'wishlist:logout' %}">Logout</a>
</nav>

<div class="d-flex align-content-center flex-wrap flex-column align-items-center justify-content-center" style="height: 100vh;">
    <h1 class="pb-4">Submit</h1>

    <form  id="create-wishlist">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input class="btn login_btn btn-outline-warning" type="submit" value="Submit">
    </form>
</div>

<div>
    <table id="wishlist-table" class="table table-dark table-hover" style="height:200px; margin:auto auto;">
        <tr>
        <th>Nama</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        <tbody>
            {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Sesi terakhir dilihat dari cookies -->
<p class="text-center p-4">Sesi terakhir login: {{ last_login }}</p>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $(document).ready(function(){
        $.get("/wishlist/json", function(data) => {
            var html = '';
            $(response).each(function(index, barang) {
                html += "<tr><td>" + barang.nama_barang + "</td><td>" + barang.harga_barang + "</td><td>" + barang.deskripsi + "</td></tr>" 
            })
            $("#table tbody").append(html)
        });
    });

    $("#create-wishlist").click(function(e) {
        e.preventDefault();
        $.ajax({
            url: "/wishlist/ajax/submit",
            data: {
                'nama_barang':nama_barang,
                'harga_barang': harga_barang,
                'deskripsi': deskripsi,
            },
            type: 'POST',
            dataType: 'json',
            success: function(response) {
                var instance = JSON.parse(response["data"]);
                var html = '';
                $(response).each(function(index, barang) {
                    html += "<tr><td>" + barang.nama_barang + "</td><td>" + barang.harga_barang + "</td><td>" + barang.deskripsi + "</td></tr>" 
            })
            $("#table tbody").append(html)
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        });
    });</script>

{% endblock content %}